[package]
name = "social"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
social = "_"

[dev-addresses]
social = "d4f78f76dc5b0a54dfd587c8b708a5f66d1faaa6ab3dbf9ef8e5a56ea8ca665b"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"